### ISSUE TITLE
Endpoint link is broken

### ISSUE THREAD

**Issue by kyptin** [sarah256/fortune-api#2]
Thanks for this! I plan to use it for my class this morning. :-)

I think Heroku changed things on you, but the current link that you have in the README (which also appears [here](https://www.programmableweb.com/api/fortune-rest-api), FYI) is broken. Instead of https://fortuneapi.heroku.com/, the correct link is now https://fortuneapi.herokuapp.com/.

**Comment by sarah256** [comment]
Thanks so much for pointing this out - it should be all set now
